"""initial schema

Revision ID: 22621ad022bb
Revises:
Create Date: 2026-09-02 20:11:48.125316
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "22621ad022bb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("YOUTUBE", "UPLOAD", name="source_type", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "DOWNLOADING",
                "TRANSCRIBING",
                "ANALYZING",
                "GENERATING_CLIPS",
                "COMPLETED",
                "FAILED",
                name="project_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("source_video_path", sa.Text(), nullable=True),
        sa.Column("audio_path", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(
        "ix_projects_status_created_at", "projects", ["status", "created_at"], unique=False
    )
    op.create_table(
        "clip_candidates",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("start_segment_index", sa.Integer(), nullable=True),
        sa.Column("end_segment_index", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("hook", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("transcript_excerpt", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("hook_score", sa.Float(), nullable=True),
        sa.Column("curiosity_score", sa.Float(), nullable=True),
        sa.Column("emotion_score", sa.Float(), nullable=True),
        sa.Column("clarity_score", sa.Float(), nullable=True),
        sa.Column("value_score", sa.Float(), nullable=True),
        sa.Column("shareability_score", sa.Float(), nullable=True),
        sa.Column("duration_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SELECTED",
                "REJECTED",
                "RENDERING",
                "RENDERED",
                "FAILED",
                name="candidate_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_clip_candidates_end_after_start")
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100", name=op.f("ck_clip_candidates_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_clip_candidates_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clip_candidates")),
    )
    op.create_index(
        op.f("ix_clip_candidates_project_id"), "clip_candidates", ["project_id"], unique=False
    )
    op.create_index(
        "ix_clip_candidates_project_score", "clip_candidates", ["project_id", "score"], unique=False
    )
    op.create_table(
        "transcripts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("language_probability", sa.Float(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_transcripts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
        sa.UniqueConstraint("project_id", name=op.f("uq_transcripts_project_id")),
    )
    op.create_table(
        "generated_clips",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("subtitle_path", sa.Text(), nullable=True),
        sa.Column("thumbnail_path", sa.Text(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("filesize_bytes", sa.BigInteger(), nullable=True),
        sa.Column("has_burned_subtitles", sa.Boolean(), nullable=False),
        sa.Column("encoder", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["clip_candidates.id"],
            name=op.f("fk_generated_clips_candidate_id_clip_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_clips")),
        sa.UniqueConstraint("candidate_id", name=op.f("uq_generated_clips_candidate_id")),
    )
    op.create_table(
        "transcript_segments",
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_transcript_segments_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint("transcript_id", "index", name="uq_segment_index"),
    )
    op.create_index(
        op.f("ix_transcript_segments_transcript_id"),
        "transcript_segments",
        ["transcript_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcript_segments_transcript_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_table("generated_clips")
    op.drop_table("transcripts")
    op.drop_index("ix_clip_candidates_project_score", table_name="clip_candidates")
    op.drop_index(op.f("ix_clip_candidates_project_id"), table_name="clip_candidates")
    op.drop_table("clip_candidates")
    op.drop_index("ix_projects_status_created_at", table_name="projects")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
